version: '3.7'
services:
  interior-shop:
    build:
      context: .
      dockerfile: Dockerfile
    image: davidrochholz/interior-shop
    working_dir: /usr/src/interior-shop
    env_file:
      - ./docker.env
    ports:
      - 8000:8000
    command: ["./wait-for-it.sh", "mysql:3306", "--", "sh", "entrypoint.sh"]
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    env_file:
      - ./docker.env

